-- Seed data for InternTrack internship aggregator
-- Populates initial companies, sources, and sample internships

-- Insert sample companies
INSERT INTO companies (name, domain, linkedin_url) VALUES
('Google', 'google.com', 'https://linkedin.com/company/google'),
('Microsoft', 'microsoft.com', 'https://linkedin.com/company/microsoft'),
('Meta', 'meta.com', 'https://linkedin.com/company/meta'),
('Apple', 'apple.com', 'https://linkedin.com/company/apple'),
('Amazon', 'amazon.com', 'https://linkedin.com/company/amazon'),
('Netflix', 'netflix.com', 'https://linkedin.com/company/netflix'),
('Tesla', 'tesla.com', 'https://linkedin.com/company/tesla'),
('JPMorgan Chase', 'jpmorganchase.com', 'https://linkedin.com/company/jpmorganchase'),
('Goldman Sachs', 'goldmansachs.com', 'https://linkedin.com/company/goldman-sachs'),
('McKinsey & Company', 'mckinsey.com', 'https://linkedin.com/company/mckinsey');

-- Insert data sources
INSERT INTO sources (name, type, base_url, is_active) VALUES
('Google Careers', 'scrape', 'https://careers.google.com', true),
('Microsoft Careers', 'scrape', 'https://careers.microsoft.com', true),
('Meta Careers', 'scrape', 'https://careers.meta.com', true),
('Apple Jobs', 'scrape', 'https://jobs.apple.com', true),
('Amazon Jobs', 'scrape', 'https://amazon.jobs', true),
('Greenhouse API', 'api', 'https://api.greenhouse.io', true),
('Lever API', 'api', 'https://api.lever.co', true),
('Workday API', 'api', 'https://api.workday.com', true),
('Exa.ai Search', 'api', 'https://api.exa.ai', true),
('Manual Entry', 'manual', null, true);

-- Insert sample internships (using company and source IDs)
WITH company_ids AS (
  SELECT id, name FROM companies WHERE name IN ('Google', 'Microsoft', 'Meta', 'Apple', 'Amazon')
),
source_ids AS (
  SELECT id, name FROM sources WHERE name IN ('Google Careers', 'Microsoft Careers', 'Meta Careers', 'Apple Jobs', 'Amazon Jobs')
)
INSERT INTO internships (
  title, 
  company_id, 
  source_id, 
  url, 
  application_url, 
  description, 
  location, 
  is_remote, 
  work_type, 
  posted_at, 
  application_deadline,
  normalized_role, 
  relevant_majors, 
  skills, 
  eligibility_year, 
  internship_cycle, 
  is_program_specific, 
  source_type, 
  canonical_hash
) VALUES
(
  'Software Engineering Intern - Summer 2025',
  (SELECT id FROM company_ids WHERE name = 'Google'),
  (SELECT id FROM source_ids WHERE name = 'Google Careers'),
  'https://careers.google.com/jobs/results/123456789',
  'https://careers.google.com/jobs/results/123456789/apply',
  'Join Google as a Software Engineering Intern and work on cutting-edge projects that impact billions of users worldwide. You will collaborate with experienced engineers, contribute to real products, and gain hands-on experience with large-scale systems.',
  'Mountain View, CA',
  false,
  'paid',
  NOW() - INTERVAL '2 hours',
  NOW() + INTERVAL '30 days',
  'Software Engineering',
  ARRAY['Computer Science', 'Software Engineering', 'Computer Engineering'],
  ARRAY['Python', 'Java', 'C++', 'Algorithms', 'Data Structures'],
  ARRAY['Junior', 'Senior'],
  'Summer 2025',
  false,
  'company_career_page',
  'google-swe-intern-summer-2025-mountain-view'
),
(
  'STEP Intern - Google (First and Second Year Students)',
  (SELECT id FROM company_ids WHERE name = 'Google'),
  (SELECT id FROM source_ids WHERE name = 'Google Careers'),
  'https://careers.google.com/jobs/results/step-program',
  'https://careers.google.com/jobs/results/step-program/apply',
  'The Student Training in Engineering Program (STEP) is a 12-week internship for first and second-year undergraduate students with a passion for computer science and technology.',
  'Multiple Locations',
  false,
  'paid',
  NOW() - INTERVAL '1 day',
  NOW() + INTERVAL '45 days',
  'Software Engineering',
  ARRAY['Computer Science', 'Computer Engineering', 'Any'],
  ARRAY['Programming Fundamentals', 'Problem Solving', 'Teamwork'],
  ARRAY['Freshman', 'Sophomore'],
  'Summer 2025',
  true,
  'company_career_page',
  'google-step-intern-summer-2025-multiple'
),
(
  'Product Management Intern - Summer 2025',
  (SELECT id FROM company_ids WHERE name = 'Microsoft'),
  (SELECT id FROM source_ids WHERE name = 'Microsoft Careers'),
  'https://careers.microsoft.com/us/en/job/1234567/Product-Management-Intern',
  'https://careers.microsoft.com/us/en/job/1234567/apply',
  'As a Product Management Intern at Microsoft, you will work alongside experienced PMs to define product strategy, analyze market opportunities, and drive product development for Microsoft''s cloud and productivity solutions.',
  'Redmond, WA',
  false,
  'paid',
  NOW() - INTERVAL '6 hours',
  NOW() + INTERVAL '25 days',
  'Product Management',
  ARRAY['Business', 'Computer Science', 'Engineering', 'Economics'],
  ARRAY['Product Strategy', 'Market Analysis', 'Data Analysis', 'Communication'],
  ARRAY['Junior', 'Senior'],
  'Summer 2025',
  false,
  'company_career_page',
  'microsoft-pm-intern-summer-2025-redmond'
),
(
  'Data Science Intern - Meta University',
  (SELECT id FROM company_ids WHERE name = 'Meta'),
  (SELECT id FROM source_ids WHERE name = 'Meta Careers'),
  'https://careers.meta.com/jobs/1234567890',
  'https://careers.meta.com/jobs/1234567890/apply',
  'Meta University is an immersive program designed to provide hands-on experience in data science and analytics. Interns will work on real projects that help billions of people connect and share.',
  'Menlo Park, CA',
  false,
  'paid',
  NOW() - INTERVAL '3 days',
  NOW() + INTERVAL '20 days',
  'Data Science',
  ARRAY['Computer Science', 'Statistics', 'Mathematics', 'Data Science'],
  ARRAY['Python', 'SQL', 'Machine Learning', 'Statistics', 'Data Visualization'],
  ARRAY['Sophomore', 'Junior'],
  'Summer 2025',
  true,
  'company_career_page',
  'meta-ds-intern-meta-university-summer-2025'
),
(
  'Software Engineering Intern - Remote',
  (SELECT id FROM company_ids WHERE name = 'Apple'),
  (SELECT id FROM source_ids WHERE name = 'Apple Jobs'),
  'https://jobs.apple.com/en-us/details/200123456',
  'https://jobs.apple.com/en-us/details/200123456/apply',
  'Join Apple''s software engineering team as a remote intern. Work on innovative projects for iOS, macOS, and other Apple platforms while collaborating with world-class engineers.',
  'Remote',
  true,
  'paid',
  NOW() - INTERVAL '12 hours',
  NOW() + INTERVAL '35 days',
  'Software Engineering',
  ARRAY['Computer Science', 'Software Engineering'],
  ARRAY['Swift', 'Objective-C', 'iOS Development', 'macOS Development'],
  ARRAY['Junior', 'Senior'],
  'Summer 2025',
  false,
  'company_career_page',
  'apple-swe-intern-remote-summer-2025'
),
(
  'Business Analyst Intern - Finance',
  (SELECT id FROM company_ids WHERE name = 'Amazon'),
  (SELECT id FROM source_ids WHERE name = 'Amazon Jobs'),
  'https://amazon.jobs/en/jobs/1234567',
  'https://amazon.jobs/en/jobs/1234567/apply',
  'Amazon Finance is seeking a Business Analyst Intern to support financial planning, analysis, and strategic initiatives. This role offers exposure to Amazon''s diverse business segments and financial operations.',
  'Seattle, WA',
  false,
  'paid',
  NOW() - INTERVAL '18 hours',
  NOW() + INTERVAL '28 days',
  'Business Analyst',
  ARRAY['Business', 'Finance', 'Economics', 'Mathematics'],
  ARRAY['Excel', 'SQL', 'Financial Modeling', 'Data Analysis'],
  ARRAY['Junior', 'Senior'],
  'Summer 2025',
  false,
  'company_career_page',
  'amazon-ba-intern-finance-summer-2025-seattle'
);